[book]
authors = ["Daniel"]
language = "en"
multilingual = false
src = "src"
title = "Mdbook Theme"

[output.html]
auto_render_katex = true
additional-css = ["custom.css"]

[output.katex]

[preprocessor.katex]
renderers = ["html"]
macros = "macros.txt"
